### PR TITLE
Fix incorrect lark_parser module name

### PR DESCRIPTION
**Pull request by rstyd**
This PR addresses #494.

### CODE REVIEW

**Comment by rstyd** [comment]
The issue is actually the documentation itself. The documentation states we need the `lark-parser` module, but the module is actually called `lark_parser`. It's very subtle.

**Comment by j-ogas** [comment]
Right, but @reidpr just showed that `lark-parser` works for him. I'm wondering if it is a pip3 version issue?

**Comment by rstyd** [comment]
Ohhh. Now that is odd.

**Comment by reidpr** [comment]
Let's please discuss the bug on the bug's issue.

**Pull request closed without merging**
