### PR TITLE
ch-tar2dir: better error message

### LINKED ISSUE #340: ch-tar2dir: clarify error message if DIR doesn't exist
@samcmill reports in PR #335 review that `ch-tar2dir` gives a confusing error message if `DIR` doesn't exist. One can tickle this usability bug if one misinterprets `DIR` to be the image directory, not its parent:

```
$ ch-tar2dir alpine.tar.gz ch-img
creating new image ch-img/alpine
mkdir: cannot create directory 'ch-img/alpine': No such file or directory
$ mkdir ch-img
$ ch-tar2dir alpine.tar.gz ch-img
creating new image ch-img/alpine
ch-img/alpine unpacked ok
$ ls ch-img/alpine/
WEIRD_AL_YANKOVIC  dev  home  media  proc  run   srv  tmp  var
bin                etc  lib   mnt    root  sbin  sys  usr
```

### PR DESCRIPTION
**Pull request by reidpr**
Closes #340.

### CODE REVIEW

**Comment by reidpr** [comment]
@samcmill, you reported the usability issue; do you think this is a reasonable fix?

**Comment by reidpr** [comment]
Thanks @samcmill.

I find it counter-intuitive at times too. The reasoning for having it this way is as follows, though whether it's *good* reasoning is open to judgement. It's for consistency; all the scripts have an argument of the form "put the output artifact in this directory", with the name itself computed for less typing. It might be a little more intuitive for `ch-docker2tar`:

```
$ ch-docker2tar alpine36 /var/tmp                   # current behavior
```

vs.

```
$ ch-docker2tar alpine36 /var/tmp/alpine36.tar.gz  # alternate: more expressive but longer to type
```

We did actually have it the way you suggest (argument is image path, not its parent) for a while, but people tended to make the opposite error, assuming that it was the parent like the other scripts.

**Comment by samcmill** [comment]
My perspective is that `ch-run` is the "core" command.  In that light, consistency would primarily mean being consistent with `ch-run` which takes the image path, not the parent path, as it's argument.

(This is just provide some more color on my perspective and why I personally find it counter intuitive.  I'm not suggesting you re-open this topic or make any changes.  The new error message will immediately correct me if I misinterpret this in the future.)

**Comment by reidpr** [comment]
Thanks! I hadn't thought of that way. That's a valuable perspective.

**Comment by reidpr** [comment]
I agree on `fatal`. Rusty suggested it too I think.

**Pull request merged**
