### PR TITLE
support extended globs on --unset-env

### PR DESCRIPTION
**Pull request by adrecord**
PR for #1311

### CODE REVIEW

**Comment by reidpr** [comment]
Nice tidy little PR. Thank you! I'd like to add a couple things before merging: (1) documentation (likely just a few words or a sentence) and (2) a test. My guess is the latter would go in the existing test `@test 'ch-run --unset-env'` in `ch-run_misc.bats`. Would you like to add those or should we do it?

**Comment by adrecord** [comment]
@reidpr added docs and tests with last commit.  Please let me know if anything else is needed.  Thanks!

**Comment by adrecord** [comment]
@reidpr This PR is ready for review.  Is requesting a review normally done as a comment or is there a way to do in the GitHub UI?  The Reviewers section I see at the top right of the PR doesn't seem to let me request one.  It only lets me Convert to Draft.  Thanks.

**Comment by reidpr** [comment]
Yeah I wonder if only members of the org can request a reviewer. Commenting is fine. Thanks!

**Review by reidpr — APPROVED** [review]

**Pull request merged**
