### PR TITLE
Fix hardcoded calls to gcc.

### PR DESCRIPTION
**Pull request by olifre**
To be open for choice of different C compilers,
honour CC variable.

### CODE REVIEW

**Comment by reidpr** [comment]
So you're right of course, but there's a bit of history there. The reason it's GCC is that Intel CC likes to link everything with extra Intel shared libraries, which don't get copied into the images and the test suite fails. I suppose we could just puke if `CC=icc`.

**Comment by olifre** [comment]
If it's only `icc`, I think this would be the better choice. The problem with hardcoding `CC` is that some distributions complain about packages doing that, and theoretically, users may want to use e.g. `clang` as system compiler. 

Then we should probably do that both for the `test/Makefile` and `examples/syscall/Makefile`, right?

**Comment by reidpr** [comment]
> Then we should probably do that both for the `test/Makefile` and `examples/syscall/Makefile`, right?

Yes, probably. I believe `bin/Makefile` does it already (implicitly).

**Comment by olifre** [comment]
It seems the call in `examples/syscall/Makefile` was removed in the meantime, and only `test/Makefile` remains. I have rebased on current master and changed the PR to:
- Remove the hardcoded call to `gcc` and use `$(CC)` instead. 
- Error out if the `$(CC)` ends with `icc`. 

This is right now only done in `test/Makefile` since that seems to be the only explicit call.

**Comment by reidpr** [comment]
Thanks @olifre! I'll merge this after 0.10 which we are trying to push out the door.

**Pull request merged**
