### PR TITLE
re-mount read-only using existing flags

### PR DESCRIPTION
**Pull request by reidpr**
Use `statvfs(3)` to pass existing mount flags (except the ones we want to change) to `mount(2)` when we remount the new root filesystem read-only. This addresses #9 and #401.

Passes Travis and full-scope on my box. These tests do not, however, exercise the specific cases identified in #401. I'd like to try it on that before merging.

### CODE REVIEW

**Comment by j-ogas** [comment]
Ran successfully on front-end and computes in both cray and non-cray production environments.

**Comment by reidpr** [comment]
Does it work with an image on our NFS filesystems now too?

**Comment by reidpr** [comment]
@rodwalker, could you give this PR a try in your environment and see if it fixes the bug you reported in #401?

**Comment by j-ogas** [comment]
> Does it work with an image on our NFS filesystems now too?

Yes!

**Pull request merged**
