### PR TITLE
ch-builder2tar: work for ch-image images containing slash

### PR DESCRIPTION
**Pull request by reidpr**
Addresses #957.

### CODE REVIEW

**Review by shanegoff — COMMENTED** [review]
The changes look minimal. How can we restart the CI to make sure it passes?

**Comment by reidpr** [comment]
> How can we restart the CI to make sure it passes?

Apparently re-running the jobs in the GitHub web app attempts a merge with current master, so that's all it needs.

**Comment by shanegoff** [comment]
After some manual testing it looks like there are other issues.

`ch-builder2squash` doesn't work with an image with a slash in it 
```
$:~/code/charliecloud/examples/lustre$ ch-builder2squash -b ch-image lustre/testme .
builder: ch-image
exporting
/usr/local/bin/ch-builder2tar: 137: cd: can't cd to /var/tmp/rgoff/ch-image/img/lustre/testme
-rw-rw-r-- 1 rgoff rgoff 0 Jan 26 15:40 /tmp/ch-builder2squash.JHJiop/lustre.testme.tar
creating new image /tmp/ch-builder2squash.JHJiop/lustre.testme
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

I also found that tar2dir doesn't work either with an image with a slash in it

```
$o:~/code/charliecloud/examples/lustre$ ch-builder2tar -b ch-image lustre/testme .
builder: ch-image
exporting
/usr/local/bin/ch-builder2tar: 137: cd: can't cd to /var/tmp/rgoff/ch-image/img/lustre/testme
compressing
-rw-rw-r-- 1 rgoff rgoff 20 Jan 26 15:43 ./lustre.testme.tar.gz
$:~/code/charliecloud/examples/lustre$ ls
 Dockerfile   lustre.testme.tar.gz   test.bats
$:~/code/charliecloud/examples/lustre$ ch-tar2dir lustre.testme.tar.gz .
creating new image ./lustre.testme
/usr/local/bin/ch-tar2dir: 129: cannot create ./lustre.testme/WEIRD_AL_YANKOVIC: Directory nonexistent
$:~/code/charliecloud/examples/lustre$ ls
 Dockerfile   lustre.testme.tar.gz   test.bats
```

**Comment by reidpr** [comment]
OK, I manually audited all the scripts that seemed to interact with images and fixed `ch-pull2dir`. `ch-builder2squash` works now. I couldn't reproduce the problem with `ch-builder2tar`, though it does seem to fail on images that don't exist (issue #971).

The test suite doesn't really know how to deal with slash images either (issue #972). So, I have not updated anything to catch other similar bugs.

At some point I would like a test that exercises all the possible image conversions. I hesitate to put effort into that now since we are hoping to restructure the commands. But, I think we are OK for now.

**Review by shanegoff — APPROVED** [review]
Everything works as expected

**Pull request merged**
