### PR TITLE
add credits to README

### PR DESCRIPTION
**Pull request by reidpr**
@mej, @olifre, @mcv21, @jlowellwofford: Is this credit OK with you, and if not, what do you prefer?

Feel free to contact me privately if you don't want to discuss it in public.

### CODE REVIEW

**Comment by olifre** [comment]
Perfectly fine with me, thanks! 👍

**Comment by jlowellwofford** [comment]
Looks good to me.

**Comment by mcv21** [comment]
Fine by me, thanks for checking.

**Comment by mej** [comment]
LGTM

**Pull request merged**
