### PR TITLE
Fix docker check if docker is a wrapper for podman

### PR DESCRIPTION
**Pull request by pagrubel**
This fixes the docker check if there is a docker wrapper for podman.

### CODE REVIEW

**Comment by pagrubel** [comment]
What's the magic to get the tests to pass for this simple PR?

**Review by reidpr — COMMENTED** [review]
Pat, thanks for the patch. I am sorry to let it sit so long. @mphinney1100 referred the brackets problem to me. Indeed, this caused the test failure. Changing to single brackets made the glob pattern not work any more, so I pushed an alternative. Also I moved the error message to later.

Can you please try the changed PR and let us know if it works for you?

**Comment by reidpr** [comment]
This time the test failure is spurious (see PR #1707).

**Comment by pagrubel** [comment]
Thank you for the fix. It does work on the system that we encountered problems on.

**Pull request merged**
