### PR TITLE
strtok_r(3): initialize saveptr to NULL

### PR DESCRIPTION
**Pull request by loveshack**

### CODE REVIEW

**Comment by reidpr** [comment]
Addresses #1048.

**Comment by reidpr** [comment]
Good catch @loveshack; thank you! I pushed a new commit with some style tidying. Does this still work for you? If so I will merge.

Note the [strtok_r(3)](https://man7.org/linux/man-pages/man3/strtok.3.html) man page mentions `saveptr` needing to be `NULL` sometimes. Maybe that is the problem.

**Comment by reidpr** [comment]
I think the CI failure is unrelated but I will look more carefully later today.

**Comment by loveshack** [comment]
Yes, it still works.

For what it's worth, POSIX says you don't need to initialize the save
pointer, and I don't think GCC could tell if you needed to.

In related news, while trying to understand what was happening I built
with -O3 and got this:

```
ch_misc.c: In function ‘msg.constprop’:
ch_misc.c:154:7: error: array subscript 4 is above array bounds of
‘const char *[4]’ [-Werror=array-bounds]
  154 |       fputs(VERBOSE_LEVELS[level], stderr);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ch_misc.c:28:13: note: while referencing ‘VERBOSE_LEVELS’
   28 | const char *VERBOSE_LEVELS[] = { "error", "warning", "info", "debug" };
      |             ^~~~~~~~~~~~~~
```

**Pull request merged**
