### PR TITLE
Openmpi 3.1.3 build with UCX don't use HFI patch

### PR DESCRIPTION
**Pull request by heasterday**
This PR should resolve issues with host launches and guest launches within the test suite while skipping serial launches of mpi applications pending issue 295. Guest launches require the command line option "--host localhost" to prevent Openmpi attempting to startup on remote hosts within a multinode allocation. 
Dockerfile.openmpi likely needs some clean up. The current way I'm lugging around the patch file and applying it may need to be changed as well.

### CODE REVIEW

**Comment by j-ogas** [comment]
Relevant to #226 and #295.

**Comment by j-ogas** [comment]
Preliminary testing was successful. Note that @heasterday instructed me to `export OMPI_MCA_btl="^vader"`. He explained to me why we needed to do this but I can't seem to remember why. In any case, I thought it would be a good idea to document this step.

**Comment by heasterday** [comment]
Within our test suite at least one of the images has a version of gcc that gets bitten by the following issue:
https://github.com/open-mpi/ompi/issues/6014
Where a certain atomic operation gets treated as a no-op, this results in the vader btl hanging. For the sake of testing Howard's UCX patch I used the parameter Jordan showed to remove vader from use. This was simply a workaround to test UCX's behavior without that issue potentially being in the mix.

Until Openmpi comes out with a new release, building images from openmpi's nightly tarball for 3.1.3 should resolve this.

**Comment by reidpr** [comment]
Hunter, re. "nightly builds not being stable", who is concerned about stability? The OpenMPI team?

Using a nightly build pending 3.1.4 is appealing to me if the OpenMPI people are comfortable with it. If OpenMPI 3.1.4 comes out on April 1, that will mean either Charliecloud 0.9.9 (April 1) or 0.9.10 (May 6).

I don't want to disable `vader` or require users to set an environment variable.

**Comment by reidpr** [comment]
We can also consider installing a newer GCC in the relevant images. I looked briefly at those OpenMPI bugs and it seemed that was not too hard.

**Comment by reidpr** [comment]
OK, let's proceed with a PR that includes the nightly tarball. Is there a way to get a specific nightly tarball, to retain reproducible builds on our end?

**Comment by heasterday** [comment]
We could grab the January 11th 3.1.x tarball and test with that as I believe it has the vader fix, the hugepages fix is still pending on that branch though but that is a separate issue.

**Comment by reidpr** [comment]
@heasterday: Can you look over my changes? I have tests passing on both a cluster and my workstation. If you're happy, I'll merge.

**Comment by heasterday** [comment]
@reidpr Looks good to me

**Pull request merged**
