### PR TITLE
enable Arch and Alpine fakeroot support

### LINKED ISSUE #1295: `ch-image --force`: support Arch

### PR DESCRIPTION
**Pull request by loveshack**
This gets the fakeroot support working using FAKEROOTDONTTRYCHOWN
(which I'll try to get documented) from #1362.  However, running
`ch-test build -b ch-image` fails with
```
...
error: scope '' invalid
found: /home/mdehsdl3/.local/share/doc/charliecloud/examples/serial/obspy/Dockerfile.skipped
found: /home/mdehsdl3/.local/share/doc/charliecloud/examples/chtest/Build

generate build_auto.bats ...
ok

executing build phase tests ...
Error: Duplicate test name(s) in file "/tmp/ch-test.tmp.mdehsdl3/build_auto.bats": test_build_hello test_builder_to_archive_hello
```
I haven't taken time to understand the test setup so I don't have a fix.  I have
tested the change separately, though.

Also there's a configure change to fix the test for FNM_EXTMATCH and
allow the build to work (on Debian 11) with current source.  Otherwise it fails
redefining FNM_EXTMATCH in ch_misc.c.

### CODE REVIEW

**Comment by heasterday** [comment]
Hey Dave thanks for the contribution! For testing this change I would recommend something like the following:  
* To run just the archlinux fakeroot tests: `ch-test -s full -b ch-image --file=../test/build/61_force-auto.bats:archlinux`
* To run just the alpine fakeroot tests: `ch-test -s full -b ch-image --file=../test/build/61_force-auto.bats:alpine`

The issue with Alpine Linux does appear to be fixed but I was still seeing failures with Arch that appear to be resolved by removing `glibc` and `util-linux` from the fakeroot config. Is this consistent with what you are seeing?

**Comment by reidpr** [comment]
@loveshack Do you want to do the testing fixes or should we?

**Comment by reidpr** [comment]
> Also there's a configure change to fix the test for FNM_EXTMATCH and
> allow the build to work (on Debian 11) with current source. Otherwise it fails
> redefining FNM_EXTMATCH in ch_misc.c.

FWIW, it builds fine on my Debian 11.3 amd64 box.

**Comment by reidpr** [comment]
> However, running
> `ch-test build -b ch-image` fails with

I wonder if it's an argument order problem. Does `ch-test -b ch-image build` work?

FWIW, under Python 3.9.2 your line works fine.

**Comment by loveshack** [comment]
You wrote: 

> Hey Dave thanks for the contribution! For testing this change I would
> recommend something like the following:
> * To run just the archlinux fakeroot tests: `ch-test -s full -b
> ch-image --file=../test/build/61_force-auto.bats:archlinux`

All that does is skip >100 cases.

Was I doing something wrong just using the simple invocation?

> * To run just the alpine fakeroot tests: `ch-test -s full -b ch-image
> --file=../test/build/61_force-auto.bats:alpine`
> The issue with Alpine Linux does appear to be fixed but I was still
> seeing failures with Arch that appear to be resolved by removing
> `glibc` and `util-linux` from the fakeroot config. Is this consistent
> with what you are seeing?

Oh, I see, sorry.  However, the installation succeeds anyhow.  There are
other failures reported which might also seem worrying but aren't fatal.

If you remove the installation of glibc, you may end up with the
situation I saw, as in the comment above.  I don't know how
common/problematic that is, but it's quite obscure if you hit it.

Regardless, I think it would be useful for the fakeroot structure to
allow including one or more information messages, perhaps saying
something like "ignore X" or "try Z if Y fails".  Otherwise, perhaps the
expected error/warning messages from the installation could be filtered
out.  It's all a bit of a mess...

**Comment by loveshack** [comment]
> @loveshack Do you want to do the testing fixes or should we?

Sorry, I don't know my way around to do it.

**Comment by loveshack** [comment]
>> Also there's a configure change to fix the test for FNM_EXTMATCH and
>> allow the build to work (on Debian 11) with current source. Otherwise it fails
>> redefining FNM_EXTMATCH in ch_misc.c.
>
> FWIW, it builds fine on my Debian 11.3 amd64 box.

Oh...  I don't understand the difference.  The configure test as written
isn't correct anyway, is it?

**Comment by reidpr** [comment]
OK, I pushed a commit to add the tests.

Hunter's suggestion to remove `glibc` and `util-linux` from Arch makes the tests pass. Based on the comment above, this does seem brittle. I agree it would be good if Charliecloud knew that the errors causing non-zero exit were spurious, but that seems very difficult.

**Review by heasterday — APPROVED** [review]

**Comment by heasterday** [comment]
@reidpr This is good to merge. Please note that I updated the nvidia example for a new signing key.

**Pull request merged**
