### PR TITLE
ch-image: add layer git cache

### PR DESCRIPTION
**Pull request by rstyd**
This PR addresses #583.

### CODE REVIEW

**Comment by reidpr** [comment]
Replaces old PR #824?

**Comment by rstyd** [comment]
Additional Work Required:

- [ ] Get all the tests working. Some are head scratchers for me. 
- [ ] Add a few additional tests. In particular for no_cache. 
- [ ] Establish a minimum version of git.

**Review by reidpr — COMMENTED** [review]
Discussed offline.

**Comment by reidpr** [comment]
Closing in favor of newer PR #1276.

**Pull request closed without merging**
