### PR TITLE
Ignore leading and trailing spaces in Sphinx shebang

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/hpc/charliecloud/issues/909

### CODE REVIEW

**Review by reidpr — APPROVED** [review]
This looks good, thanks!

Unfortunately Travis has broken again, so this (and every other PR) will have to wait a little while before merging, until our CI is fixed.

**Comment by reidpr** [comment]
@hroncok Is it OK if I push commits to your branch? Specifically I would like to merge in the fixed CI stuff once it is ready. If not, that's fine; I'll let you know when it is ready and you can do it.

**Comment by hroncok** [comment]
You can do whatever you need with this branch.

**Comment by reidpr** [comment]
Passes tests and merged. Thanks so much!

**Pull request merged**
