### PR TITLE
make docs build with old Sphinx

### PR DESCRIPTION
**Pull request by reidpr**
Addresses #565.

I tested this using the highest versions of Sphinx (1.2.3), docutils (0.14), and sphinx-rtd-theme (0.2.4) available in EPEL7, but installed using `pip3`. I have not tried it on actual CentOS or RHEL; can you please test that?

The number of changes to the `.rst` file was surprisingly small, but the results look OK.

### CODE REVIEW

**Comment by j-ogas** [comment]
The epel 7 package, `python3-sphinx`, which provides `sphinx-build` version 1.2.3, packages the executable in /usr/bin as `sphinx-build-3.6`. Thus, the configure sets documentation build to no when it fails to find `sphinx-build`.

**Comment by reidpr** [comment]
> packages the executable in /usr/bin as `sphinx-build-3.6`.

Well that's convenient. 🙄

Debian packages have a notion of "alternatives" and would set up a `sphinx-build` symlink. Do the EPEL RPMs have an equivalent?

Also, one could configure with `--with-sphinx-build=/usr/bin/sphinx-build-3.6`; would that be acceptable?

**Comment by j-ogas** [comment]
> Debian packages have a notion of "alternatives" and would set up a `sphinx-build` symlink. Do the EPEL RPMs have an equivalent?

Yes, if the alternatives are defined in the package spec file. However, the python3-sphinx package [spec file](https://src.fedoraproject.org/rpms/python3-sphinx/blob/epel7/f/python3-sphinx.spec) does not appear to have them.

FWIIW, this specific package is dead and only maintained on epel 7 (there is a different package for epel 8). 
> 
> Also, one could configure with `--with-sphinx-build=/usr/bin/sphinx-build-3.6`; would that be acceptable?

This seems reasonable to me. I can account for this conditionally in the spec file; still much cleaner than the doc patch we have now.

**Comment by olifre** [comment]
I'm sorry I only notice this now, but this PR broke the build on Gentoo Linux (and potentially others). 
The problem is that:
```
sphinx_python=$(head -1 "$SPHINX" | sed -E 's/^..//')
```
does not work. On Gentoo, any python tool which is installed with multiple implementations is wrappered:
```
$ ls -la $(which sphinx-build)
lrwxrwxrwx 1 root root 31  4. Jan 18:44 /usr/bin/sphinx-build -> ../lib/python-exec/python-exec2
$ head /usr/lib/python-exec/python-exec2
#!/usr/bin/python-exec2c
# vim:fileencoding=utf-8:ft=python
# (c) 2012-2016 Michał Górny
# Released under the terms of the 2-clause BSD license.
#
# This is not the script you are looking for. This is just a wrapper.
# The actual scripts of this application were installed
# in subdirectories of /usr/lib/python-exec.
# You are most likely looking for one of those.
```
This is done so the system can runtime-switch implementation (like Debian's `update-alternatives`). 

I'm not sure about the best way to work around this here, at least checking the first line of `sphinx-build` is not portable enough.

**Comment by olifre** [comment]
Maybe the "easiest" would be to have a flag to force the assumption that the `sphinx_python` is the same as the system's `python`?

**Comment by reidpr** [comment]
Thank you @olifre! No statue of limitations. I agree that you've found a bug. Shall we discuss a solution in issue #629?

**Comment by olifre** [comment]
Agreed, thanks :+1: .

**Pull request merged**
