### PR TITLE
Spack example

### PR DESCRIPTION
**Pull request by j-ogas**
This the first pass at a Spack example. 

Couple things I would like to draw your attention to:

1. The latest push fails the Travis tests. At a glance, the [error](https://travis-ci.org/hpc/charliecloud/jobs/362447830) seems to be related to the sphinx doc
2. This examples takes over 2 hours to complete

Right now test.bats runs the Spack unit tests and installs the openmpi 3.0.1 package (and its dependencies, see comment in test.bats). The unit tests take approximately 7 minutes and the package installation takes about 2 hours (1:40:62). I thought it would be cool to showcase the installation of a beefy package like openmpi or paraview but the test time -- which does not include the Dockerfile image build time --  seems to be a bit much.

We could just install a smaller package that does not have a legion of dependencies. Could it be that the unit tests alone are sufficient?

### CODE REVIEW

**Comment by reidpr** [comment]
Addresses issue #130.

**Comment by reidpr** [comment]
> The latest push fails the Travis tests. At a glance, the error seems to be related to the sphinx doc

This seems to be a hiccup in VM setup. It happens from time to time. I restarted the job (511.8) and it passed.

> This examples takes over 2 hours to complete

Yes, that's too long.

I think the unit tests plus installing a small package would be sufficient.

As for the unit test failures mentioned in the issue, go ahead and paste the errors.

**Comment by j-ogas** [comment]
> I think the unit tests plus installing a small package would be sufficient.

Changed the installation package to ~~m4~~ libsigsegv. 

> As for the unit test failures mentioned in the issue, go ahead and paste the errors

Turns out 2 of the 3 errors were caused by a Spack bug and were [fixed](https://github.com/spack/spack/pull/7652). The unit tests appear to report 4 categories: passed, skipped, failed, and **xfailed**. The two errors fixed in the patch were listed as failed. The remaining error is listed as xfailed with the following output: 

` XFAIL lib/spack/spack/test/cmd/help.py::test_reuse_after_help`

However, `echo $?` returns 0. So do we care? The only reference to this test on the Spack unit test [documentation](http://spack.readthedocs.io/en/latest/spack.test.cmd.html) is as follows:

```
spack.test.cmd.help.test_reuse_after_help()
Test spack help can be called twice with the same SpackCommand.
```

With a quick google I am unable to find any bug reports or issues from this particular test.

Finally, because the Dockerfile doesn't install certain packages (e.g. Subversion, gnupg2, etc.) some tests are skipped:

```
=========================== short test summary info ============================
SKIP [1] lib/spack/spack/test/cmd/flake8.py:81: flake8 is not installed.
SKIP [36] /spack/lib/spack/spack/test/llnl/util/lock.py:154: requires filesystem: '/nfs/tmp2/jogas'
SKIP [1] lib/spack/spack/test/mirror.py:130: requires subversion to be installed
SKIP [1] lib/spack/spack/test/cmd/gpg.py:55: These tests require gnupg2
SKIP [4] lib/spack/spack/test/svn_fetch.py:39: requires subversion to be installed
SKIP [1] lib/spack/spack/test/mirror.py:144: requires subversion, git, and mercurial to be installed
SKIP [1] lib/spack/spack/test/module_parsing.py:92: Depends on defined module fn
SKIP [36] /spack/lib/spack/spack/test/llnl/util/lock.py:154: requires filesystem: '/p/lscratch*/jogas'
SKIP [1] lib/spack/spack/test/packaging.py:337: only works with Mach-o objects
XFAIL lib/spack/spack/test/cmd/help.py::test_reuse_after_help
```
The above SKIPs account for 82 tests (1079 tests in total). How do we feel about that?

**Comment by j-ogas** [comment]
Some improvements: (1) removed unnecessary bootstrap command and (2) removed redundant package installation.

Building the Spack environment - via bootstrap - was unnecessary for unit tests and package installation demonstration purposes. The total test time (including a fresh image build) has been reduced to approximately 20 minutes. 

```
 ✓ spack/unittests
 ✓ spack/installpackage
 ✓ spack/clean

3 tests, 0 failures

real	12m46.262s
user	7m42.453s
sys	1m36.111s

```

The output above is from the linux time command on a script containing the following:

```
ch-build -t spack . \
&& ch-docker2tar spack /var/tmp/images \
&& ch-tar2dir /var/tmp/tarballs/spack.tar.gz /var/tmp/images/ \
&& ../../../test/bats/bin/bats test.bats
```

**Pull request closed without merging**
